import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google'
import '../globals.css';

import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode,
  params: { locale: string }
};

const inter = Inter({ subsets: ['latin'] });

export default async function RootLayout({ children, params: { locale } }: Props) {
  const language = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${inter.className}`}>
        <NextIntlClientProvider messages={language}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}